# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  cmake:
    cmds:
      - env "CXX=/usr/local/opt/llvm/bin/clang++" cmake -B build -S . -GNinja
  compile:
    cmds:
      - cmake --build build
  execute:
    cmds:
      - ./build/02-lines
  execute-with-san:
    cmds:
      - ASAN_OPTIONS=detect_leaks=1 LSAN_OPTIONS=suppressions=leak.supp ./build/02-lines

